/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as CelebritiesRouteImport } from './routes/celebrities'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProsRouteImport } from './routes/pros'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as BarberSlugRouteImport } from './routes/barber.$slug'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as CelebritySlugRouteImport } from './routes/celebrity.$slug'
import { Route as CelebrityNewRouteImport } from './routes/celebrity.new'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveNewRouteImport } from './routes/live.new'
import { Route as ProHandleRouteImport } from './routes/pro.$handle'
import { Route as ProNewRouteImport } from './routes/pro.new'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as UNewRouteImport } from './routes/u.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebritiesRoute = CelebritiesRouteImport.update({
  id: '/celebrities',
  path: '/celebrities',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsRoute = ProsRouteImport.update({
  id: '/pros',
  path: '/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const BarberSlugRoute = BarberSlugRouteImport.update({
  id: '/barber/$slug',
  path: '/barber/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebritySlugRoute = CelebritySlugRouteImport.update({
  id: '/celebrity/$slug',
  path: '/celebrity/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebrityNewRoute = CelebrityNewRouteImport.update({
  id: '/celebrity/new',
  path: '/celebrity/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveNewRoute = LiveNewRouteImport.update({
  id: '/live/new',
  path: '/live/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHandleRoute = ProHandleRouteImport.update({
  id: '/pro/$handle',
  path: '/pro/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProNewRoute = ProNewRouteImport.update({
  id: '/pro/new',
  path: '/pro/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UNewRoute = UNewRouteImport.update({
  id: '/u/new',
  path: '/u/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/celebrities': typeof CelebritiesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/pros': typeof ProsRoute
  '/sponsors': typeof SponsorsRoute
  '/barber/$slug': typeof BarberSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/celebrity/new': typeof CelebrityNewRoute
  '/live/new': typeof LiveNewRoute
  '/pro/$handle': typeof ProHandleRoute
  '/pro/new': typeof ProNewRoute
  '/u/$handle': typeof UHandleRoute
  '/u/new': typeof UNewRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/celebrities': typeof CelebritiesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/pros': typeof ProsRoute
  '/sponsors': typeof SponsorsRoute
  '/barber/$slug': typeof BarberSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/celebrity/new': typeof CelebrityNewRoute
  '/live/new': typeof LiveNewRoute
  '/pro/$handle': typeof ProHandleRoute
  '/pro/new': typeof ProNewRoute
  '/u/$handle': typeof UHandleRoute
  '/u/new': typeof UNewRoute
  '/live': typeof LiveIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/celebrities': typeof CelebritiesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/pros': typeof ProsRoute
  '/sponsors': typeof SponsorsRoute
  '/barber/$slug': typeof BarberSlugRoute
  '/book/$slug': typeof BookSlugRoute
  '/celebrity/$slug': typeof CelebritySlugRoute
  '/celebrity/new': typeof CelebrityNewRoute
  '/live/new': typeof LiveNewRoute
  '/pro/$handle': typeof ProHandleRoute
  '/pro/new': typeof ProNewRoute
  '/u/$handle': typeof UHandleRoute
  '/u/new': typeof UNewRoute
  '/live/': typeof LiveIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/auth'
    | '/bookings'
    | '/celebrities'
    | '/classes'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/pricing'
    | '/pros'
    | '/sponsors'
    | '/barber/$slug'
    | '/book/$slug'
    | '/celebrity/$slug'
    | '/celebrity/new'
    | '/live/new'
    | '/pro/$handle'
    | '/pro/new'
    | '/u/$handle'
    | '/u/new'
    | '/live/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/affiliates'
    | '/auth'
    | '/bookings'
    | '/celebrities'
    | '/classes'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/pricing'
    | '/pros'
    | '/sponsors'
    | '/barber/$slug'
    | '/book/$slug'
    | '/celebrity/$slug'
    | '/celebrity/new'
    | '/live/new'
    | '/pro/$handle'
    | '/pro/new'
    | '/u/$handle'
    | '/u/new'
    | '/live'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliates'
    | '/auth'
    | '/bookings'
    | '/celebrities'
    | '/classes'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/pricing'
    | '/pros'
    | '/sponsors'
    | '/barber/$slug'
    | '/book/$slug'
    | '/celebrity/$slug'
    | '/celebrity/new'
    | '/live/new'
    | '/pro/$handle'
    | '/pro/new'
    | '/u/$handle'
    | '/u/new'
    | '/live/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CelebritiesRoute: typeof CelebritiesRoute
  ClassesRoute: typeof ClassesRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  PricingRoute: typeof PricingRoute
  ProsRoute: typeof ProsRoute
  SponsorsRoute: typeof SponsorsRoute
  BarberSlugRoute: typeof BarberSlugRoute
  BookSlugRoute: typeof BookSlugRoute
  CelebritySlugRoute: typeof CelebritySlugRoute
  CelebrityNewRoute: typeof CelebrityNewRoute
  LiveNewRoute: typeof LiveNewRoute
  ProHandleRoute: typeof ProHandleRoute
  ProNewRoute: typeof ProNewRoute
  UHandleRoute: typeof UHandleRoute
  UNewRoute: typeof UNewRoute
  LiveIndexRoute: typeof LiveIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrities': {
      id: '/celebrities'
      path: '/celebrities'
      fullPath: '/celebrities'
      preLoaderRoute: typeof CelebritiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros': {
      id: '/pros'
      path: '/pros'
      fullPath: '/pros'
      preLoaderRoute: typeof ProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barber/$slug': {
      id: '/barber/$slug'
      path: '/barber/$slug'
      fullPath: '/barber/$slug'
      preLoaderRoute: typeof BarberSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity/$slug': {
      id: '/celebrity/$slug'
      path: '/celebrity/$slug'
      fullPath: '/celebrity/$slug'
      preLoaderRoute: typeof CelebritySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity/new': {
      id: '/celebrity/new'
      path: '/celebrity/new'
      fullPath: '/celebrity/new'
      preLoaderRoute: typeof CelebrityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/new': {
      id: '/live/new'
      path: '/live/new'
      fullPath: '/live/new'
      preLoaderRoute: typeof LiveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/$handle': {
      id: '/pro/$handle'
      path: '/pro/$handle'
      fullPath: '/pro/$handle'
      preLoaderRoute: typeof ProHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/new': {
      id: '/pro/new'
      path: '/pro/new'
      fullPath: '/pro/new'
      preLoaderRoute: typeof ProNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/new': {
      id: '/u/new'
      path: '/u/new'
      fullPath: '/u/new'
      preLoaderRoute: typeof UNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CelebritiesRoute: CelebritiesRoute,
  ClassesRoute: ClassesRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  PricingRoute: PricingRoute,
  ProsRoute: ProsRoute,
  SponsorsRoute: SponsorsRoute,
  BarberSlugRoute: BarberSlugRoute,
  BookSlugRoute: BookSlugRoute,
  CelebritySlugRoute: CelebritySlugRoute,
  CelebrityNewRoute: CelebrityNewRoute,
  LiveNewRoute: LiveNewRoute,
  ProHandleRoute: ProHandleRoute,
  ProNewRoute: ProNewRoute,
  UHandleRoute: UHandleRoute,
  UNewRoute: UNewRoute,
  LiveIndexRoute: LiveIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
